### ISSUE TITLE
Can't manage to successfully install this

### ISSUE THREAD

**Issue by neutrobox** [PaladinsDev/Presence#1]
Said in the title, I did all the steps correctly but on Discord it's showing up as Paladins - Public Test.

**Comment by MatthewSH** [comment]
Due to Hi-Rez legal team and the consistent hypocrisy and the allowing of certain companies/sites to monopolize the 3rd party area without giving others a fair shot...the servers have been shut down. 

If you find this to be unfair or have a problem with how Hi-Rez has treated us please feel free to contact legal@hirezstudios.com and express your concerns or you can private message /u/Xienen on Reddit and express your frustrations with him. 

PaladinsPresence, PaladinsNinja, Assets, and Maps will no longer have development and anything that required servers have been shut down and all developer packages are put into maintenance mode. 

We will not support the double standards that Hi-Rez holds for developers within this community. Unless they no longer contradict themselves and make “reminders” that the can shut any of us down at any time, none of these services will be Returning. 

Halfpetal LLC and development has been shifted to an upcoming hero shooter made by another company who seems to care about the product and the players. We’re working with the company to help and encourage a friendly environment for players and developers alike. We will no longer support Hi-Rez in any other venture until they take control of their legal department and actually do something about it.
